x-app_environment: &app_environment
  environment:
    # Common
    BACKEND_PORT: ${BACKEND_PORT}

services:
  app:
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:3000"
    build:
      context: .
